layout_spectrum: 0.0435016
color:
  saturation: 0.434479
  lightness: 0.4776866
  brandStrength: 0.6181525
  brandColors:
    - '#A19987'
    - '#E7E4DE'
    - '#010101'
    - '#007AFF'
    - '#C62127'
  rhythmicContrast: 0.6628777
typography_spectrum: 0.4677766
name: DCR Photography
